/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotterygame1;
import java.util.Random;

/**
 *
 * @author jeanreyes
 */
public class LotteryGame1 extends javax.swing.JFrame {

    /**
     * Creates new form LotteryGame1
     */
    public LotteryGame1() {
        initComponents();
        jTextArea1.append("Lottery Game Example\n");
        
        
        //jTextArea1.append("Click button 2 to restart the game");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(95, 300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int selectionCount = 18;
        int lotterySelection[] = new int[selectionCount];
        int selectionBound = 63;

        Random seed = new Random();
        Random rv1 = new Random(selectionBound);
        rv1.setSeed(seed.nextInt(100000));

        for(int i = 0; i < selectionCount; i++) {
            lotterySelection[i] = rv1.nextInt(selectionBound) + 1;
            jTextArea1.append(lotterySelection[i] + " ");
        }
        
        int take3[] = generateUniqueNumbers(4, selectionBound);
        int take4[] = generateUniqueNumbers(5, selectionBound);
        int take5[] = generateUniqueNumbers(6, selectionBound);
    
        jTextArea1.append("\nTake 3: ");
        printArray(take3, jTextArea1);

        jTextArea1.append("Take 4: ");
        printArray(take4, jTextArea1);

        jTextArea1.append("Take 5: ");
        printArray(take5, jTextArea1);
        
        
        jTextArea1.append("\nIf you want to play again press the jbutton1\n");
        
    }//GEN-LAST:event_jButton1ActionPerformed
public static int[] generateUniqueNumbers(int size, int bound) {
    Random rand = new Random();
    int[] result = new int[size];
    int count = 0;

    while (count < size) {
        int num = rand.nextInt(bound) + 1;

        boolean exists = false;
        for (int i = 0; i < count; i++) {
            if (result[i] == num) {
                exists = true;
                break;
            }
        }

        if (!exists) {
            result[count] = num;
            count++;
        }
    }

    return result;
}

public static void printArray(int[] arr, javax.swing.JTextArea area) {
    for (int num : arr) {
        area.append(num + " ");
    }
    area.append("\n");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotteryGame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

