/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotterygame1;
import java.util.Random;

/**
 *
 * @author jeanreyes
 */
public class LotteryGame1 extends javax.swing.JFrame {

    /**
     * Creates new form LotteryGame1
     */
    public LotteryGame1() {
        initComponents();
        universalOutputConsole.append("Lottery Game Example\n");
        
        
        //jTextArea1.append("Click button 2 to restart the game");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unviersalContentPane = new javax.swing.JScrollPane();
        universalOutputConsole = new javax.swing.JTextArea();
        standardButtonLeft = new javax.swing.JButton();
        standardButtonRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        universalOutputConsole.setColumns(20);
        universalOutputConsole.setRows(5);
        unviersalContentPane.setViewportView(universalOutputConsole);

        standardButtonLeft.setText("Start");
        standardButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardButtonLeftActionPerformed(evt);
            }
        });

        standardButtonRight.setText("Set Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(standardButtonLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(standardButtonRight)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addComponent(unviersalContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(unviersalContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standardButtonLeft)
                    .addComponent(standardButtonRight))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void standardButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardButtonLeftActionPerformed

        int selectionCount = 18;
        int lotterySelection[] = new int[selectionCount];
        int selectionBound = 63;

        Random seed = new Random();
        Random rv1 = new Random(selectionBound);
        rv1.setSeed(seed.nextInt(100000));

        for(int i = 0; i < selectionCount; i++) {
            lotterySelection[i] = rv1.nextInt(selectionBound) + 1;
            universalOutputConsole.append(lotterySelection[i] + " ");
        }
        
        int take3[] = generateUniqueNumbers(4, selectionBound);
        int take4[] = generateUniqueNumbers(5, selectionBound);
        int take5[] = generateUniqueNumbers(6, selectionBound);
    

        // Winning tickets
        int win3[] = generateUniqueNumbers(4, selectionBound);
        int win4[] = generateUniqueNumbers(5, selectionBound);
        int win5[] = generateUniqueNumbers(6, selectionBound);

        // Bonus number
        int bonus = new Random().nextInt(selectionBound) + 1;

        // Display player's tickets
        universalOutputConsole.append("\nTake 3: ");
        printArray(take3, universalOutputConsole);

        universalOutputConsole.append("Take 4: ");
        printArray(take4, universalOutputConsole);

        universalOutputConsole.append("Take 5: ");
        printArray(take5, universalOutputConsole);

        // Display winning tickets
        universalOutputConsole.append("\nWinning Take 3: ");
        printArray(win3, universalOutputConsole);

        universalOutputConsole.append("Winning Take 4: ");
        printArray(win4, universalOutputConsole);

        universalOutputConsole.append("Winning Take 5: ");
        printArray(win5, universalOutputConsole);

        universalOutputConsole.append("\nBonus Number: " + bonus + "\n\n");
        
        
        universalOutputConsole.append("\nIf you want to play again press the jbutton1\n");
        
    }//GEN-LAST:event_standardButtonLeftActionPerformed
public static int[] generateUniqueNumbers(int size, int bound) {
    Random rand = new Random();
    int[] result = new int[size];
    int count = 0;

    while (count < size) {
        int num = rand.nextInt(bound) + 1;

        boolean exists = false;
        for (int i = 0; i < count; i++) {
            if (result[i] == num) {
                exists = true;
                break;
            }
        }

        if (!exists) {
            result[count] = num;
            count++;
        }
    }

    return result;
}

public static void printArray(int[] arr, javax.swing.JTextArea area) {
    for (int num : arr) {
        area.append(num + " ");
    }
    area.append("\n");
}

public static boolean isExactMatch(int[] a, int[] b) {
    if (a.length != b.length) return false;

    for (int i = 0; i < a.length; i++) {
        if (a[i] != b[i]) {
            return false;
        }
    }
    return true;
}

public static boolean containsNumber(int[] arr, int num) {
    for (int n : arr) {
        if (n == num) return true;
    }
    return false;
}


public void checkWin(int[] player, int[] winning, int bonus, int prize, String label) {

    if (isExactMatch(player, winning)) {

        if (containsNumber(player, bonus)) {
            prize *= 10;
            universalOutputConsole.append(label + " WINNER with BONUS! Prize: $" + prize + "\n");
        } else {
            universalOutputConsole.append(label + " WINNER! Prize: $" + prize + "\n");
        }

    } else {
        universalOutputConsole.append(label + " not a winner.\n");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LotteryGame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LotteryGame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton standardButtonLeft;
    private javax.swing.JButton standardButtonRight;
    private javax.swing.JTextArea universalOutputConsole;
    private javax.swing.JScrollPane unviersalContentPane;
    // End of variables declaration//GEN-END:variables
}

